sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean asciidoctor

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: build/asciidoc/html5/  # or remove this line to upload from root of repo
    github_token: $GITHUB_TOKEN  
    on:
      branch: master

